# Generated by Django 5.1.2 on 2024-10-13 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cId', models.IntegerField(verbose_name='ID категории')),
                ('cName', models.CharField(choices=[('Food', 'Еда'), ('Clothes', 'Одежда'), ('HApp', 'Бытовая техника'), ('Services', 'Услуги')], default='-', max_length=8, verbose_name='Категория')),
            ],
            options={
                'verbose_name': ('Категория',),
                'verbose_name_plural': ('Категории',),
                'ordering': ['cName'],
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sId', models.IntegerField(verbose_name='ID магазина')),
                ('sName', models.CharField(max_length=40, verbose_name='Магазин')),
                ('sPrice', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': ('Магазин',),
                'ordering': ['sName'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pId', models.IntegerField(verbose_name='ID сотрудника')),
                ('pName', models.CharField(max_length=40, verbose_name='Название')),
                ('pDate', models.DateField(verbose_name='Дата публикации товара')),
                ('pCount', models.IntegerField(verbose_name='Количество товара')),
                ('pPhoto', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('pCategory', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='smallshop.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': ('Продукт',),
                'verbose_name_plural': ('Продукты',),
                'ordering': ['pName'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId', models.IntegerField(verbose_name='ID покупателя')),
                ('custName', models.CharField(max_length=40, verbose_name='Покупатель')),
                ('pId', models.ManyToManyField(max_length=40, to='smallshop.products', verbose_name='ID Товара')),
                ('sId', models.ManyToManyField(max_length=40, to='smallshop.shops', verbose_name='ID Магазина')),
            ],
            options={
                'verbose_name': ('Покупатель',),
                'verbose_name_plural': ('Покупатели',),
                'ordering': ['custName'],
            },
        ),
    ]
