# Generated by Django 5.1.2 on 2024-10-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
        migrations.AddField(
            model_name='shops',
            name='pId',
            field=models.ManyToManyField(max_length=40, to='smallshop.products', verbose_name='ID продукта'),
        ),
    ]
